version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=masterKey

  backend:
    build: 
      context: ./backend
      args:
        datestamp: ${datestamp}
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_API_KEY=masterKey
    depends_on:
      - meilisearch

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: http://192.168.0.70:5000
        VITE_API_KEY: super-secret-key
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

